name: 🧪 Django CI/CD

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    name: 🧪 Tests & Quality Checks
    runs-on: ubuntu-latest

  security:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 🔒 Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: 🔍 Run Bandit security linter
        run: |
          bandit -r . -f json -o bandit-report.json || true

      - name: 🛡️ Check dependencies for vulnerabilities
        run: |
          safety check --json --output safety-report.json || true

      - name: 📊 Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json

  build-test:
    name: 🐳 Docker Build Test
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🐳 Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: sed:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🧪 Test Docker image
        run: |
          docker run --rm sed:test python manage.py check

  summary:
    name: 📋 CI Summary
    runs-on: ubuntu-latest
    needs: [test, security, build-test]
    if: always()

    steps:
      - name: 📊 CI Results Summary
        run: |
          echo "## 📋 CI/CD Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| 🧪 Tests | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 🔒 Security | ${{ needs.security.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 🐳 Docker Build | ${{ needs.build-test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.test.result }}" == "success" && "${{ needs.security.result }}" == "success" && "${{ needs.build-test.result }}" == "success" ]]; then
            echo "✅ **All checks passed!** Ready for deployment." >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Some checks failed.** Please review the errors above." >> $GITHUB_STEP_SUMMARY
          fi
